# Generated by Django 3.0.7 on 2020-06-17 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('puede_editar', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=100)),
                ('f_nacimiento', models.DateField()),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ejemplo.Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=1000)),
                ('fecha', models.DateField()),
                ('likes', models.IntegerField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='posts', to='ejemplo.Usuario')),
            ],
        ),
    ]
